**🎯 Objective:**
You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

**🧠 Project Description:**
A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

**Project Tasks**

**1. Data Creation**:**Create suitable arrays to represent students, subjects, and their marks.


In [ ]:
import numpy as np
st_marks=np.array([[97,85,90,87],
                   [78,80,67,75],
                   [88,79,75,69],
                   [60,58,55,48]])
print(f" created table of marks with st_name and subject :\n {st_marks}")

 created table of marks with st_name and subject :
 [[97 85 90 87]
 [78 80 67 75]
 [88 79 75 69]
 [60 58 55 48]]


**2.Data Exploration**:*Explore the properties of these arrays — such as their dimensions, size, and structure.


In [ ]:
print(f" Dimension of st_marks is {st_marks.ndim} 'D")
print(f" Size of the  st_marks is {st_marks.size} elements")
print(f" Structure of st_marks is {st_marks.shape}")

 Dimension of st_marks is 2 'D
 Size of the  st_marks is 16 elements
 Structure of st_marks is (4, 4)


**3.Data Transformation:** Perform necessary reshaping and reorganization of the data to suit various operations.

In [ ]:
re_shape=st_marks.reshape(2,8)
print(f" Reshaped array :\n {re_shape}")   # reshaped to 2 rows and 8 columns

print("\n")

trans=st_marks.T
print(f"transposed array :\n {trans}")

 Reshaped array :
 [[97 85 90 87 78 80 67 75]
 [88 79 75 69 60 58 55 48]]


transposed array :
 [[97 78 88 60]
 [85 80 79 58]
 [90 67 75 55]
 [87 75 69 48]]


4.**Data Combination**:Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset

In [ ]:
add_marks_v=np.array([78,85,69,72])
marks_update_v=np.vstack((st_marks,add_marks_v))
print(f" Adding marks for all student's:\n  {marks_update_v}")
add_marks_h=np.array([[87],[67],[56],[43]])
marks_update_h=np.hstack((st_marks,add_marks_h))
print(f" Adding new student marks:\n {marks_update_h}")

 Adding marks for all student's:
  [[97 85 90 87]
 [78 80 67 75]
 [88 79 75 69]
 [60 58 55 48]
 [78 85 69 72]]
 Adding new student marks:
 [[97 85 90 87 87]
 [78 80 67 75 67]
 [88 79 75 69 56]
 [60 58 55 48 43]]


5.**Data Modification**:Apply operations to update marks, remove data, or identify unique information.


In [ ]:
marks_update_v[0][2]=99
print(f" After updateting marks:\n {marks_update_v} \n")

delete_marks=np.delete(marks_update_v,2)
print(f"After deleting :\n{delete_marks} \n")

unique_marks=np.unique(marks_update_v)
print(f"Unique_information of marks :{unique_marks}")


 After updateting marks:
 [[97 85 99 87]
 [78 80 67 75]
 [88 79 75 69]
 [60 58 55 48]
 [78 85 69 72]] 

After deleting :
[97 85 87 78 80 67 75 88 79 75 69 60 58 55 48 78 85 69 72] 

Unique_information of marks :[48 55 58 60 67 69 72 75 78 79 80 85 87 88 97 99]


**6.Data Type Handling:** Demonstrate how the same data can exist in different data types and how changes affect results.

In [ ]:
print(f" The actuale datatype is {marks_update_v.dtype}")
diffdtype=marks_update_v.astype(float)
print(f" updated datatype is:\n {diffdtype}") # here data type is converted to float


 The actuale datatype is int64
 updated datatype is:
 [[97. 85. 99. 87.]
 [78. 80. 67. 75.]
 [88. 79. 75. 69.]
 [60. 58. 55. 48.]
 [78. 85. 69. 72.]]


**7. Copy and View Behavior**:Show the difference between creating a full copy of an array and creating a view of the same data.

In [ ]:
# COPY
marks_copy=marks_update_v.copy()
marks_copy[0,0]=100
print(f"Original marks : {marks_update_v[0,0]}")
print(f"Copied marks : {marks_copy[0,0]}")

Original marks : 97
Copied marks : 100


In [ ]:
#VIEW
marks_view=marks_update_v.view()
marks_view[0,1]=99
print(f"Original marks: {marks_update_v[0,1]}")
print(f"Viewed marks : {marks_view[0,1]}")

Original marks: 99
Viewed marks : 99
